//
//  MoviesPresenter.swift
//  MovieDB
//
//  Created by Igor Andruskiewitsch on 18/02/2019.
//  Copyright (c) 2019 Igor Andruskiewitsch. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MoviesPresenter {
  func presentMovies(_ movies: [Movies.ViewModel]?)
  var viewController: MoviesDisplay? { get set }
}

class MoviesPresenterImpl: MoviesPresenter {
  weak var viewController: MoviesDisplay?
  
  // MARK: Do something
  
  func presentMovies(_ movies: [Movies.ViewModel]?) {
    DispatchQueue.main.async {  [weak self] in
      guard let `self` = self else {
        return
      }
      
      guard let `movies` = movies else {
        self.viewController?.displayError("Ocurrió un error al buscar las peliculas")
        return
      }
      
      guard movies.count != 0 else {
        self.viewController?.displayError("No se encontraron peliculas")
        return
      }

      self.viewController?.displayMovies(movies: movies)
    }
  }
}
