//
//  MoviesModels.swift
//  MovieDB
//
//  Created by Igor Andruskiewitsch on 18/02/2019.
//  Copyright (c) 2019 Igor Andruskiewitsch. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation
import UIKit
import RealmSwift


// MARK: Service/View structs
enum Movies
{
  
  //  MARK: Request
  struct Request
  {
  }
  
  //  MARK: Response
  struct Response
  {
    var movies: [Movie] = []
    
    init? (json movies: [[String: Any]]) {
      for json in movies {
        if let movie = Movie(json: json) {
          self.movies.append(movie)
        }
      }
    }
  }
  
  //  MARK: ViewModel
  struct ViewModel
  {
    var id: Int?
    var title: String?
    var overview: String?
    var releaseDate: Date?
    var poster: UIImage?
  }
  
}

