//
//  MoviesModels.swift
//  MovieDB
//
//  Created by Igor Andruskiewitsch on 18/02/2019.
//  Copyright (c) 2019 Igor Andruskiewitsch. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RealmSwift

// MARK: REALM object
class Movie: Object {
  @objc dynamic var id: Int = 0
  @objc dynamic var title: String?
  @objc dynamic var overview: String?
  @objc dynamic var releaseDate: Date?
  @objc dynamic var posterUrl: String?
  
  convenience init?(json: [String: Any]) {
    self.init()

    guard
      let id = json["id"] as? Int,
      let title = json["title"] as? String,
      let description = json["overview"] as? String,
      let releaseDateString = json["release_date"] as? String,
      let posterUrl = json["poster_path"] as? String else {
        print("error al parsear la pelicula: ")
        print(json)
        return nil
    }
    
    self.id = id
    self.title = title
    self.overview = description
    self.releaseDate = Date(string: releaseDateString, format: .snakeFormat)
    self.posterUrl = posterUrl
  }
  
}

// MARK: Service/View structs
enum Movies
{
  
  struct Request
  {
  }
  
  struct Response
  {
    var movies: [Movie] = []
    
    init? (json movies: [[String: Any]]) {
      for json in movies {
        if let movie = Movie(json: json) {
          self.movies.append(movie)
        }
      }
    }
  }
  
  struct ViewModel
  {
    var title: String?
    var overview: String?
    var releaseDate: Date?
    var poster: UIImage?
  }
  
}

