//
//  MoviesModels.swift
//  MovieDB
//
//  Created by Igor Andruskiewitsch on 18/02/2019.
//  Copyright (c) 2019 Igor Andruskiewitsch. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Movies
{
  // MARK: Use cases
  
  enum List
  {
    struct Request
    {
    }
    struct Response
    {
      var movies: [ViewModel] = []
      
      init? (json movies: [[String: Any]]) {
        for json in movies {
          if let movie = ViewModel(json: json) {
            self.movies.append(movie)
          }
        }
      }
      
    }
    struct ViewModel
    {
      var title: String?
      var description: String?
      var releaseDate: Date?
      var posterUrl: String?
      var poster: UIImage?
      
      init?(json: [String: Any]) {
        guard let title = json["title"] as? String,
            let description = json["overview"] as? String,
            let releaseDateString = json["release_date"] as? String,
            let posterUrl = json["poster_path"] as? String else {
              print("error al parsear la pelicula: ")
              print(json)
              return nil
        }
        
        self.title = title
        self.description = description
        self.releaseDate = Date(string: releaseDateString, format: .snakeFormat)
        self.posterUrl = posterUrl
      }
      
    }
  }
}
