//
//  MoviesInteractor.swift
//  MovieDB
//
//  Created by Igor Andruskiewitsch on 18/02/2019.
//  Copyright (c) 2019 Igor Andruskiewitsch. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MoviesBusinessLogic
{
  func fetchMovies()
}

protocol MoviesDataStore
{
  //var name: String { get set }
}

class MoviesInteractor: MoviesBusinessLogic, MoviesDataStore
{
  var presenter: MoviesPresentationLogic?
  var worker: MoviesWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func fetchMovies()
  {
    worker = MoviesWorker()
    worker?.findAll(completion: presenter!.presentMovies)
  }
  
}
